from dateutil.tz import tzoffset

seconds_per_hour = 60*60

# Timezone string mappings from TimeAPI
# http://github.com/progrium/timeapi/blob/master/timeapi.rb
_tzoffsets = {
  'A' : +1,
  'ADT' : -3,
  'AKDT' : -8,
  'AKST' : -9,
  'AST' : -4,
  'B' : +2,
  'BST' : +1,
  'C' : +3,
  'CDT' : -5,
  'CEDT' : +2,
  'CEST' : +2,
  'CET' : +1,
  'CST' : -6,
  'D' : +4,
  'E' : +5,
  'EDT' : -4,
  'EEDT' : +3,
  'EEST' : +3,
  'EET' : +2,
  'EST' : -5,
  'F' : +6,
  'G' : +7,
  'GMT' : 0,
  'H' : +8,
  'HADT' : -9,
  'HAST' : -10,
  'I' : +9,
  'IST' : +1,
  'K' : +10,
  'L' : +11,
  'M' : +12,
  'MDT' : -6,
  'MSD' : +4,
  'MSK' : +3,
  'MST' : -7,
  'N' : -1,
  'O' : -2,
  'P' : -3,
  'PDT' : -7,
  'PST' : -8,
  'Q' : -4,
  'R' : -5,
  'S' : -6,
  'T' : -7,
  'U' : -8,
  'UTC' : 0,
  'V' : -9,
  'W' : -10,
  'WEDT' : +1,
  'WEST' : +1,
  'WET' : 0,
  'X' : -11,
  'Y' : -12,
  'Z' : 0
}

TimeZone = dict( ( k, tzoffset(k, v*seconds_per_hour) ) for k,v in _tzoffsets.iteritems() )
